name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "pro.romain.schipman@gmail.com"
          git config --global user.name "Romain Schipman"

      - name: Determine version bump
        id: version
        run: |
          # Check for labels and set the bump type accordingly
          if git log -1 --pretty=%B | grep -q 'major'; then
            echo "::set-output name=bump_type::major"
          elif git log -1 --pretty=%B | grep -q 'minor'; then
            echo "::set-output name=bump_type::minor"
          else
            echo "::set-output name=bump_type::patch"
          fi

      - name: Bump version and create changelog
        run: |
          npm version ${{ steps.version.outputs.bump_type }} -m "chore(release): bump version to %s"
          git push --follow-tags

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
