name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "pro.romain.schipman@gmail.com"
          git config --global user.name "Rosch Bot"

      - name: Determine version bump
        id: version
        run: |
          labels=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls?state=closed | jq -r '.[0].labels[].name')
          bump_type="patch"
          if echo "$labels" | grep -q "major"; then
            bump_type="major"
          elif echo "$labels" | grep -q "minor"; then
            bump_type="minor"
          fi
          echo "bump_type=$bump_type" >> $GITHUB_ENV

      - name: Bump version and create changelog
        run: |
          npm version ${{ env.bump_type }} -m "chore(release): bump version to %s"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build project
        run: npm run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
